AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TableName:
    Type: String
    Default: podfy-user
  SQSQueueName:
    Type: String
    Default: podfy-user-queue

Resources:

  DynamoDBTablePodfy: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Id"
          AttributeType: "S"
        - 
          AttributeName: "Name"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Id"
          KeyType: "HASH"
        - 
          AttributeName: "Name"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref TableName
      GlobalSecondaryIndexes: 
        - 
          IndexName: "IdHashKey"
          KeySchema: 
            - 
              AttributeName: "Id"
              KeyType: "HASH"
            - 
              AttributeName: "Name"
              KeyType: "RANGE"
          Projection: 
            NonKeyAttributes: 
              - "Name"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  QueuePodfy:
    Type: AWS::SQS::Queue
    Properties:
     QueueName: !Ref SQSQueueName
     RedrivePolicy:
       deadLetterTargetArn: !GetAtt QueuePodfyDQL.Arn
       maxReceiveCount: 3
        
  QueuePodfyDQL:
    Type: AWS::SQS::Queue
    Properties:
     QueueName: !Sub '${SQSQueueName}-dql'